### ISSUE TITLE
Existing record attributes get set to empty upon a record change.

### ISSUE THREAD

**Issue by VNRARA** [favonia/cloudflare-ddns#559] opened 2023-08-19 20:36 UTC
Existing record attributes are removed when records are updated. I'd like it not to.

**Comment by favonia** [comment] 2023-08-19 21:35
@VNRARA It was designed not to do this. Could you possibly provide more information?

**Comment by VNRARA** [comment] 2023-08-19 22:09
It's about this ones: https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/

![image](https://github.com/favonia/cloudflare-ddns/assets/3942672/bc9fae98-cb70-4b7b-870f-479d2437d459)

[logDDNSCF.txt](https://github.com/favonia/cloudflare-ddns/files/12386770/logDDNSCF.txt)

**Comment by favonia** [comment] 2023-08-19 22:59
@VNRARA Thank you. A proper fix needs the upstream to change their code https://github.com/cloudflare/cloudflare-go/issues/1371 I can however implement a hack that retrieves your existing comment before updating it. Or, you can use version 1.8.2 or below before the upstream library introduced the current behavior.

Some background: I have noticed this design issue of the upstream library [some time ago](https://github.com/cloudflare/cloudflare-go/pull/1166) but didn't double check that their final solution after getting busy at my primary job. Their design bug started to cause clearing at the version 0.60.0 of the upstream library, and that means versions after 1.8.3 are all affected. Sorry about the trouble.

**Comment by VNRARA** [comment] 2023-08-19 23:37
I'll keep using the latest version and fix the comments some later time.

**Comment by favonia** [comment] 2023-09-10 13:35
Progress: I made a PR to the upstream repo: https://github.com/cloudflare/cloudflare-go/pull/1393

**Comment by favonia** [comment] 2023-09-12 04:42
@VNRARA Progress: my PR was merged, and I'll release a new version once the dependency is updated.

**Comment by favonia** [comment] 2023-09-12 23:58
There was an issue about the release of the upstream library so I cannot (easily) use it yet: https://github.com/cloudflare/cloudflare-go/issues/1398. However, I believe such a mistake will be fixed in no time (the upstream devs are great).

**Closed** 2023-09-13 04:39 UTC
Labels: bug, blocked

**Comment by favonia** [comment] 2023-09-13 05:00
@VNRARA I believe the bug was fixed. Before I release the next official version, could you confirm that the `edge` tag will preserve existing tags and comment when updating the IP? Thank you.

**Comment by VNRARA** [comment] 2023-09-13 22:23
Hey thanks for keeping me up to date. I'm unsure what how you'd like me to test the `edge` tag.

**Comment by favonia** [comment] 2023-09-13 23:42
@VNRARA The current installation guide told you to use the image `favonia/cloudflare-ddns:latest`. You can try the next version to be released by _temporarily_ using `favonia/cloudflare-ddns:edge` instead. (Try intentionally change the IP and the tags and/or comments and see if the IP can be updated while keeping others intact.) Remember to change `edge` back to `latest` because the `edge` version is for me to try out new stuff.

**Comment by VNRARA** [comment] 2023-09-14 09:45
I'll try to report back withing 8 hours.

**Comment by favonia** [comment] 2023-09-17 13:20
@VNRARA Thanks for the confirmation.

**Comment by favonia** [comment] 2023-09-17 13:49
@VNRARA The new version with the fix has been published. It is recommended to switch back to `latest` because `edge` is for me to try out new things.
